### PR TITLE
Support for Apple / Google Pay

### PR DESCRIPTION
**Pull request by eddyinet**
My first PR. Kindly let me know of anything I should have done differently to adhere to best practices & proper etiquette.

Cheers :)

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]
The changes look very well! Can you please bump the version in the manifest file?

**Comment by eddyinet** [comment]
Missed the most obvious change ;-) All set. Thank you!

**Comment by hansemannn** [comment]
Android as well please?

**Comment by eddyinet** [comment]
🤦🏽‍♂️All set.

**Pull request merged**
